-- Sequence tang Id tu dong
CREATE SEQUENCE AUTO_INCREMENT_SEQUENCE
START WITH 1
INCREMENT BY 1;

-- Trigger tang tu dong ID

CREATE OR REPLACE TRIGGER trigger_TANGID
  BEFORE INSERT ON NHANVIEN
  FOR EACH ROW
BEGIN
  SELECT AUTO_INCREMENT_SEQUENCE.NEXTVAL
    INTO :new.MANV
  FROM dual;
END;
---------------
CREATE OR REPLACE TRIGGER trigger_TANGMAKT
  BEFORE INSERT ON KHACHTRO
  FOR EACH ROW
BEGIN
  SELECT AUTO_INCREMENT_SEQUENCE.NEXTVAL
    INTO :new.MAKT
  FROM dual;
END;
-----------------------------------------
-- VIEW KHACH TRO
CREATE VIEW VIEW_KHACHTRO
AS
SELECT KT.MAKT, KT.HOTENKT, KT.GIOITINH, KT.NGAYSINH, KT.CMND, KT.QUEQUAN, KT.DIENTHOAI, KT.NGHENGHIEP, KT.NGAYTHUE, KT.NGAYHETHAN, KT.MAPHONG, LP.LOAIPHONG, DV.TENDICHVU, SUM(P.GIAPHONG + DV.GIADV) AS "TONG TIEN"
FROM DICHVU DV INNER JOIN KHACHTRO KT ON DV.MADV = KT.MADV
    INNER JOIN PHONG P ON KT.MAPHONG = P.MAPHONG
    INNER JOIN LOAIPHONG LP ON P.MALOAIPHONG = LP.MALOAIPHONG
GROUP BY KT.MAKT, KT.HOTENKT, KT.GIOITINH, KT.NGAYSINH, KT.CMND, KT.QUEQUAN, KT.DIENTHOAI, KT.NGHENGHIEP, KT.NGAYTHUE, KT.NGAYHETHAN, KT.MAPHONG, LP.LOAIPHONG, DV.TENDICHVU

-- VIEW TIM PHONG TRONG
CREATE VIEW VIEW_PHONGTRONG
AS
SELECT P.MAPHONG, LP.LOAIPHONG, LP.SOLUONGTOIDA, P.GIAPHONG
FROM PHONG P LEFT JOIN KHACHTRO KT ON P.MAPHONG = KT.MAPHONG
    INNER JOIN LOAIPHONG LP ON P.MALOAIPHONG = LP.MALOAIPHONG
GROUP BY P.MAPHONG, LP.LOAIPHONG, LP.SOLUONGTOIDA, P.GIAPHONG
HAVING COUNT(KT.MAKT) < 1

-- VIEW SHOW PHONG
CREATE VIEW VIEW_PHONG
AS
SELECT P.MAPHONG, LP.LOAIPHONG, LP.SOLUONGTOIDA, P.GIAPHONG
FROM PHONG P INNER JOIN LOAIPHONG LP ON P.MALOAIPHONG = LP.MALOAIPHONG

-- THANH TOAN
CREATE VIEW VIEW_THANHTOAN
AS
SELECT P.MAPHONG, KT.MAKT, KT.HOTENKT, KT.NGAYTHUE, KT.NGAYHETHAN, P.GIAPHONG, DV.TENDICHVU, DV.GIADV, SUM(P.GIAPHONG + DV.GIADV) AS TONG
FROM KHACHTRO KT INNER JOIN PHONG P ON KT.MAPHONG = P.MAPHONG 
    INNER JOIN DICHVU DV ON KT.MADV = DV.MADV
GROUP BY KT.MAKT, KT.HOTENKT, KT.NGAYTHUE, KT.NGAYHETHAN, P.MAPHONG, P.GIAPHONG, DV.TENDICHVU, DV.GIADV


UPDATE KHACHTRO SET NGAYHETHAN = ADD_MONTHS(NGAYHETHAN, 1) WHERE MAPHONG = 101

-- VIEW NHAN VIEN
CREATE VIEW VIEW_NHANVIEN
AS
SELECT MANV, HOTEN, GIOITINH, NGAYSINH, CHUCVU, LUONG, QUEQUAN, DIENTHOAI, QUYEN, TAIKHOAN
FROM NHANVIEN

